include: package:lints/recommended.yaml
linter:
  rules:
    - file_names
    - prefer_const_constructors
    - sort_constructors_first
analyzer:
  exclude:
    - lib/src/bindings/libgit2_bindings.dart
