name: libgit2dart

description: Dart bindings to libgit2, provides ability to use libgit2 library in Dart and Flutter.

version: 1.2.2

homepage: https://github.com/SkinnyMind/libgit2dart

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  args: ^2.3.0
  equatable: ^2.0.3
  ffi: ^2.0.0
  meta: ^1.7.0
  path: ^1.8.1
  pub_semver: ^2.1.3

dev_dependencies:
  ffigen: ^6.0.1
  lints: ^2.0.0
  test: ^1.20.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: Libgit2dartPlugin
      macos:
        pluginClass: Libgit2dartPlugin
      windows:
        pluginClass: Libgit2dartPlugin

ffigen:
  output: "lib/src/bindings/libgit2_bindings.dart"
  headers:
    entry-points:
      - "libgit2/headers/*.h"
  name: "Libgit2"
  description: "Bindings to libgit2"
  comments:
    style: any
    length: full
