name: libgit2dart
description: Dart bindings to libgit2
version: 0.0.1

environment:
  sdk: ">=2.15.0-82.0.dev <3.0.0"

dependencies:
  archive: ^3.1.6
  args: ^2.3.0
  cli_util: ^0.3.5
  ffi: ^1.1.2

dev_dependencies:
  ffigen: ^4.0.0
  lints: ^1.0.1
  path: ^1.8.0
  test: ^1.17.5

ffigen:
  output: "lib/src/bindings/libgit2_bindings.dart"
  headers:
    entry-points:
      - "libgit2/headers/*.h"
  name: "Libgit2"
  description: "Bindings to libgit2"
  comments:
    style: any
    length: full
