name: libgit2dart
description: Dart bindings to libgit2
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^1.0.1
  ffigen: ^3.1.0-dev.1
  test: ^1.17.5
  path: ^1.8.0

ffigen:
  output: "lib/src/bindings/libgit2_bindings.dart"
  headers:
    entry-points:
      - "libgit2/headers/*.h"
  name: "Libgit2"
  description: "Bindings to libgit2"
  comments:
    style: any
    length: full
  llvm-path:
    - "/usr/lib64/libclang.so"
