name: libgit2_dart

description: Dart bindings for libgit2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  pedantic: ^1.11.0
  ffigen: ^3.0.0

ffigen:
  output: "./lib/src/libgit2_bindings.dart"
  headers:
    entry-points:
      - "./src/headers/"
  name: "Libgit2"
  description: "Bindings to libgit2"
  comments:
    style: any
    length: full
