name: libgit2dart

description: Dart bindings to libgit2.

version: 1.0.0

homepage: https://github.com/SkinnyMind/libgit2dart

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.13.0-0.0.pre.578"

dependencies:
  args: ^2.3.0
  cli_util: ^0.3.5
  ffi: ^1.1.2
  meta: ^1.7.0
  path: ^1.8.1
  pub_cache: ^0.3.1

dev_dependencies:
  ffigen: ^4.1.2
  lints: ^2.0.0
  test: ^1.20.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: Libgit2dartPlugin
      macos:
        pluginClass: Libgit2dartPlugin
      windows:
        pluginClass: Libgit2dartPlugin

ffigen:
  output: "lib/src/bindings/libgit2_bindings.dart"
  headers:
    entry-points:
      - "libgit2/headers/*.h"
  name: "Libgit2"
  description: "Bindings to libgit2"
  comments:
    style: any
    length: full
